version: "3.8"

services:
  whusdata-pipeline:
    build: .
    container_name: whusdata-pipeline
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
